version: '2'
services:
    bookservice-app:
        image: bookservice
        external_links:
            - bookservice-mysql:mysql
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/bookservice?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    bookservice-mysql:
        extends:
            file: mysql.yml
            service: bookservice-mysql
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:./central-config/docker-config/
