version: '2'
services:
    bookservice-elasticsearch:
        container_name: bookservice-elasticsearch
        image: elasticsearch:2.4.1
        # volumes:
        #     - ~/volumes/jhipster/BookService/elasticsearch/:/usr/share/elasticsearch/data/
        ports:
            - 9200:9200
            - 9300:9300
